name: C++ build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: "Make (C++)"
      run: make -C src/ all
    - name: "Make install (C++)"
      run: make -C src/ install

